language: ruby
rvm:
 - 2.2
 - jruby
 - rbx-3

sudo: required

services:
  - docker

env:
- DOCKER_COMPOSE_VERSION=1.4.2

before_script:
- sudo /etc/init.d/postgresql stop
- docker-compose build
- docker-compose run web bundle exec rails db:test:prepare

script:
- docker-compose run --rm web bundle exec rake spec
