sudo: required
services:
- docker
before_script:
- sudo /etc/init.d/postgresql stop
- docker-compose build
- docker-compose run web bundle exec rails db:test:prepare
script:
- docker-compose run --rm rekords bundle exec rake spec
