default: &default
  adapter: postgresql
  encoding: unicode
  username:
  password:
  pool: 5
development:
  <<: *default
  database: rekords_development
  password:
  username:
test:
  <<: *default
  database: rekords_test
  password:
  username:
production:
  <<: *default
  database: rekords_production
